### ISSUE TITLE
Provide a common interface for engine configuration

### ISSUE THREAD

**Issue by sukria** [PerlDancer/Dancer#22]
We have template, session and logger engines. Sometimes some engine-specific configuration is needed for them, like the templates start and stop tags, for instance.

What I have in mind would be the following:
- any engine configuration variable is registered as a regular setting
- but it's written as a YAML hashref, under the hierarchy "engines > $engine_name"
- an accessor is built in engine mother class, named "settings"

Here is an example:

```
# config.yml
warnings: 1
template: template_toolkit
...
engines:
    template_toolkit:
        start_tag: '[%'
        stop_tag: '%]'
```

In the template code:

```
sub some_engine_method {
    my ($self, ...) = @_;
    ...
    my $start_tag = $self->settings->{'start_tag'};
}
```

This reminds me of two things:
- implementing a name() accessor for all engines would be good
- implementing a Dancer::Engine class would clearly make sense
