### ISSUE TITLE
Can't store CODE items at /Dancer/Template/Abstract.pm line 149

### ISSUE THREAD

**Issue by mortiy** [PerlDancer/Dancer#817]
Such error appears:

``` javascript
{"exception":"Can't store CODE items at /usr/local/lib/perl5/site_perl/5.10.1/Dancer/Template/Abstract.pm line 149.\n",
"error":"Can't store CODE items at /usr/local/lib/perl5/site_perl/5.10.1/Dancer/Template/Abstract.pm line 149.\n"}
```

if **config.yml** contains:

``` yaml
plugins:
    Database:
        ...
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        ...
```

Removing **dbi_params** fixes problem.
