### ISSUE TITLE
Config option to set default content_type of Dancer::Plugin::Ajax

### ISSUE THREAD

**Issue by lecar-red** [PerlDancer/Dancer#840]
Add a configuration option to Dancer::Plugin::Ajax to override its default content_type 'application/json'.

In our app i'd like the plugin to default to a JSON content type w/out having to include a route or before hook.

config example:

``` yaml
   plugins:
    'Ajax':
      content_type: 'application/json'
```
